[build]
  command = "npm run build"
  publish = ".next"

# Ensure Next.js runtime is used for SSR, API routes, and Images
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  # Sharp and Prisma need to be bundled/available in Netlify Functions
  external_node_modules = ["sharp", "@prisma/client"]

[build.environment]
  NODE_VERSION = "20"
